# Generated by Django 5.2.1 on 2025-05-23 13:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_avaliacao', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('foto_produto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
