# Generated by Django 5.2.1 on 2025-05-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='cpf',
        ),
    ]
