# Generated by Django 5.2.1 on 2025-05-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_avaliacao_nome_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='nome_completo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
