# Generated by Django 5.2.1 on 2025-05-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_avaliacao_nome_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.tipoavaliacao'),
        ),
    ]
