# Generated by Django 5.2.1 on 2025-05-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_tipoavaliacao_alter_avaliacao_tipo_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tipoavaliacao'),
        ),
    ]
