# Generated by Django 5.2.1 on 2025-05-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_avaliacao_tipo_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='produtos.produto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo_suporte', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suportes', to='produtos.produto')),
            ],
        ),
    ]
