# Generated by Django 5.2.1 on 2025-11-18 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_avaliacao_produto_suporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoIntencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando no WhatsApp'), ('concluida', 'Compra concluída'), ('cancelada', 'Pedido cancelado')], default='aguardando', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('observacoes_admin', models.TextField(blank=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Intenção de compra',
                'verbose_name_plural': 'Intenções de compra',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='compra_verificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_verificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('produto', 'usuario'), name='unique_avaliacao_produto_usuario'),
        ),
        migrations.AddField(
            model_name='pedidointencao',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intencoes_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidointencao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intencoes_compra', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='pedidointencao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intencoes_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
