# Generated by Django 5.2.1 on 2025-11-18 11:32

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def create_allowed_ratings(apps, schema_editor):
    AllowedRating = apps.get_model('produtos', 'AllowedRating')
    PedidoIntencao = apps.get_model('produtos', 'PedidoIntencao')

    base_expiration = timezone.now() + timedelta(days=30)

    for pedido in PedidoIntencao.objects.filter(status='concluida').iterator():
        AllowedRating.objects.update_or_create(
            usuario_id=pedido.usuario_id,
            produto_id=pedido.produto_id,
            defaults={
                'expires_at': base_expiration,
                'used_at': None,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_pedidointencao_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_avaliacao', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_avaliacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de avaliação',
                'verbose_name_plural': 'Permissões de avaliação',
                'unique_together': {('usuario', 'produto')},
            },
        ),
        migrations.RunPython(create_allowed_ratings, migrations.RunPython.noop),
    ]
