# Generated by Django 5.2.1 on 2025-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_suportemensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='produto_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
