# Generated by Django 5.2.1 on 2025-12-18 14:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_alter_suporte_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suportemensagem',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
